mutation InsertPost(
  $content: String!
  $createdBy: Int!
  $slug: String!
  $updatedBy: Int!
  $title: String!
  $status: String!
  $summary: String!
) {
  insert_posts_one(
    object: {
      content: $content
      createdBy: $createdBy
      slug: $slug
      updatedBy: $updatedBy
      title: $title
      tagIds: [1]
      topicIds: [1]
      status: $status
      summary: $summary
    }
  ) {
    id
    slug
    title
  }
}
