/* eslint-disable */
// @generated by graphql-codegen
// This file was automatically generated and should not be edited.
import * as Types from "../../../gql/types";

import { gql } from "@apollo/client";
import * as Apollo from "@apollo/client";
const defaultOptions = {};
export type GetPostByIdQueryVariables = Types.Exact<{
  id: Types.Scalars["Int"];
}>;

export type GetPostByIdQuery = { __typename?: "query_root" } & {
  posts_by_pk?: Types.Maybe<
    { __typename?: "posts" } & Pick<
      Types.Posts,
      | "id"
      | "createdAt"
      | "updatedAt"
      | "status"
      | "slug"
      | "title"
      | "content"
      | "summary"
    > & {
        userByCreatedById: { __typename?: "users" } & Pick<
          Types.Users,
          "fullName"
        >;
        userByUpdatedById: { __typename?: "users" } & Pick<
          Types.Users,
          "fullName"
        >;
      }
  >;
};

export const GetPostByIdDocument = gql`
  query GetPostById($id: Int!) {
    posts_by_pk(id: $id) {
      id
      createdAt
      updatedAt
      status
      slug
      title
      content
      summary
      userByCreatedById {
        fullName
      }
      userByUpdatedById {
        fullName
      }
    }
  }
`;

/**
 * __useGetPostByIdQuery__
 *
 * To run a query within a React component, call `useGetPostByIdQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetPostByIdQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetPostByIdQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useGetPostByIdQuery(
  baseOptions: Apollo.QueryHookOptions<
    GetPostByIdQuery,
    GetPostByIdQueryVariables
  >
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useQuery<GetPostByIdQuery, GetPostByIdQueryVariables>(
    GetPostByIdDocument,
    options
  );
}
export function useGetPostByIdLazyQuery(
  baseOptions?: Apollo.LazyQueryHookOptions<
    GetPostByIdQuery,
    GetPostByIdQueryVariables
  >
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useLazyQuery<GetPostByIdQuery, GetPostByIdQueryVariables>(
    GetPostByIdDocument,
    options
  );
}
export type GetPostByIdQueryHookResult = ReturnType<typeof useGetPostByIdQuery>;
export type GetPostByIdLazyQueryHookResult = ReturnType<
  typeof useGetPostByIdLazyQuery
>;
export type GetPostByIdQueryResult = Apollo.QueryResult<
  GetPostByIdQuery,
  GetPostByIdQueryVariables
>;
