/* eslint-disable */
// @generated by graphql-codegen
// This file was automatically generated and should not be edited.
import { FieldPolicy, FieldReadFunction, TypePolicies, TypePolicy } from '@apollo/client/cache';
export type mutation_rootKeySpecifier = ('delete_page' | 'delete_page_by_pk' | 'insert_page' | 'insert_page_one' | 'update_page' | 'update_page_by_pk' | mutation_rootKeySpecifier)[];
export type mutation_rootFieldPolicy = {
	delete_page?: FieldPolicy<any> | FieldReadFunction<any>,
	delete_page_by_pk?: FieldPolicy<any> | FieldReadFunction<any>,
	insert_page?: FieldPolicy<any> | FieldReadFunction<any>,
	insert_page_one?: FieldPolicy<any> | FieldReadFunction<any>,
	update_page?: FieldPolicy<any> | FieldReadFunction<any>,
	update_page_by_pk?: FieldPolicy<any> | FieldReadFunction<any>
};
export type pageKeySpecifier = ('created_at' | 'id' | 'slug' | 'title' | 'updated_at' | pageKeySpecifier)[];
export type pageFieldPolicy = {
	created_at?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	title?: FieldPolicy<any> | FieldReadFunction<any>,
	updated_at?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_aggregateKeySpecifier = ('aggregate' | 'nodes' | page_aggregateKeySpecifier)[];
export type page_aggregateFieldPolicy = {
	aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	nodes?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_aggregate_fieldsKeySpecifier = ('avg' | 'count' | 'max' | 'min' | 'stddev' | 'stddev_pop' | 'stddev_samp' | 'sum' | 'var_pop' | 'var_samp' | 'variance' | page_aggregate_fieldsKeySpecifier)[];
export type page_aggregate_fieldsFieldPolicy = {
	avg?: FieldPolicy<any> | FieldReadFunction<any>,
	count?: FieldPolicy<any> | FieldReadFunction<any>,
	max?: FieldPolicy<any> | FieldReadFunction<any>,
	min?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	stddev_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	sum?: FieldPolicy<any> | FieldReadFunction<any>,
	var_pop?: FieldPolicy<any> | FieldReadFunction<any>,
	var_samp?: FieldPolicy<any> | FieldReadFunction<any>,
	variance?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_avg_fieldsKeySpecifier = ('id' | page_avg_fieldsKeySpecifier)[];
export type page_avg_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_max_fieldsKeySpecifier = ('created_at' | 'id' | 'slug' | 'title' | 'updated_at' | page_max_fieldsKeySpecifier)[];
export type page_max_fieldsFieldPolicy = {
	created_at?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	title?: FieldPolicy<any> | FieldReadFunction<any>,
	updated_at?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_min_fieldsKeySpecifier = ('created_at' | 'id' | 'slug' | 'title' | 'updated_at' | page_min_fieldsKeySpecifier)[];
export type page_min_fieldsFieldPolicy = {
	created_at?: FieldPolicy<any> | FieldReadFunction<any>,
	id?: FieldPolicy<any> | FieldReadFunction<any>,
	slug?: FieldPolicy<any> | FieldReadFunction<any>,
	title?: FieldPolicy<any> | FieldReadFunction<any>,
	updated_at?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_mutation_responseKeySpecifier = ('affected_rows' | 'returning' | page_mutation_responseKeySpecifier)[];
export type page_mutation_responseFieldPolicy = {
	affected_rows?: FieldPolicy<any> | FieldReadFunction<any>,
	returning?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_stddev_fieldsKeySpecifier = ('id' | page_stddev_fieldsKeySpecifier)[];
export type page_stddev_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_stddev_pop_fieldsKeySpecifier = ('id' | page_stddev_pop_fieldsKeySpecifier)[];
export type page_stddev_pop_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_stddev_samp_fieldsKeySpecifier = ('id' | page_stddev_samp_fieldsKeySpecifier)[];
export type page_stddev_samp_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_sum_fieldsKeySpecifier = ('id' | page_sum_fieldsKeySpecifier)[];
export type page_sum_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_var_pop_fieldsKeySpecifier = ('id' | page_var_pop_fieldsKeySpecifier)[];
export type page_var_pop_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_var_samp_fieldsKeySpecifier = ('id' | page_var_samp_fieldsKeySpecifier)[];
export type page_var_samp_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>
};
export type page_variance_fieldsKeySpecifier = ('id' | page_variance_fieldsKeySpecifier)[];
export type page_variance_fieldsFieldPolicy = {
	id?: FieldPolicy<any> | FieldReadFunction<any>
};
export type query_rootKeySpecifier = ('page' | 'page_aggregate' | 'page_by_pk' | query_rootKeySpecifier)[];
export type query_rootFieldPolicy = {
	page?: FieldPolicy<any> | FieldReadFunction<any>,
	page_aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	page_by_pk?: FieldPolicy<any> | FieldReadFunction<any>
};
export type subscription_rootKeySpecifier = ('page' | 'page_aggregate' | 'page_by_pk' | subscription_rootKeySpecifier)[];
export type subscription_rootFieldPolicy = {
	page?: FieldPolicy<any> | FieldReadFunction<any>,
	page_aggregate?: FieldPolicy<any> | FieldReadFunction<any>,
	page_by_pk?: FieldPolicy<any> | FieldReadFunction<any>
};
export type TypedTypePolicies = TypePolicies & {
	mutation_root?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | mutation_rootKeySpecifier | (() => undefined | mutation_rootKeySpecifier),
		fields?: mutation_rootFieldPolicy,
	},
	page?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | pageKeySpecifier | (() => undefined | pageKeySpecifier),
		fields?: pageFieldPolicy,
	},
	page_aggregate?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_aggregateKeySpecifier | (() => undefined | page_aggregateKeySpecifier),
		fields?: page_aggregateFieldPolicy,
	},
	page_aggregate_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_aggregate_fieldsKeySpecifier | (() => undefined | page_aggregate_fieldsKeySpecifier),
		fields?: page_aggregate_fieldsFieldPolicy,
	},
	page_avg_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_avg_fieldsKeySpecifier | (() => undefined | page_avg_fieldsKeySpecifier),
		fields?: page_avg_fieldsFieldPolicy,
	},
	page_max_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_max_fieldsKeySpecifier | (() => undefined | page_max_fieldsKeySpecifier),
		fields?: page_max_fieldsFieldPolicy,
	},
	page_min_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_min_fieldsKeySpecifier | (() => undefined | page_min_fieldsKeySpecifier),
		fields?: page_min_fieldsFieldPolicy,
	},
	page_mutation_response?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_mutation_responseKeySpecifier | (() => undefined | page_mutation_responseKeySpecifier),
		fields?: page_mutation_responseFieldPolicy,
	},
	page_stddev_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_stddev_fieldsKeySpecifier | (() => undefined | page_stddev_fieldsKeySpecifier),
		fields?: page_stddev_fieldsFieldPolicy,
	},
	page_stddev_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_stddev_pop_fieldsKeySpecifier | (() => undefined | page_stddev_pop_fieldsKeySpecifier),
		fields?: page_stddev_pop_fieldsFieldPolicy,
	},
	page_stddev_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_stddev_samp_fieldsKeySpecifier | (() => undefined | page_stddev_samp_fieldsKeySpecifier),
		fields?: page_stddev_samp_fieldsFieldPolicy,
	},
	page_sum_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_sum_fieldsKeySpecifier | (() => undefined | page_sum_fieldsKeySpecifier),
		fields?: page_sum_fieldsFieldPolicy,
	},
	page_var_pop_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_var_pop_fieldsKeySpecifier | (() => undefined | page_var_pop_fieldsKeySpecifier),
		fields?: page_var_pop_fieldsFieldPolicy,
	},
	page_var_samp_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_var_samp_fieldsKeySpecifier | (() => undefined | page_var_samp_fieldsKeySpecifier),
		fields?: page_var_samp_fieldsFieldPolicy,
	},
	page_variance_fields?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | page_variance_fieldsKeySpecifier | (() => undefined | page_variance_fieldsKeySpecifier),
		fields?: page_variance_fieldsFieldPolicy,
	},
	query_root?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | query_rootKeySpecifier | (() => undefined | query_rootKeySpecifier),
		fields?: query_rootFieldPolicy,
	},
	subscription_root?: Omit<TypePolicy, "fields" | "keyFields"> & {
		keyFields?: false | subscription_rootKeySpecifier | (() => undefined | subscription_rootKeySpecifier),
		fields?: subscription_rootFieldPolicy,
	}
};